### PR TITLE
Added SELinux functions to retrieve configuration information

### PR DESCRIPTION
**Pull request by justinethier**
Luite,

I thought you might be interested in these changes - several functions have been imported from selinux.h to retrieve configuration information. Most of these imports have been tested GHCI, although more testing could be done.

I also added a module header section and an AUTHORS file - maybe you would like these changes as well?
Thanks,

Justin

### CODE REVIEW

**Comment by luite** [comment]
hi Justin,

sorry for the late reply, I was on vacation and didn't have an internet connection. Thanks for the improvements, I'll look into them in detail later.

Luite

**Comment by justinethier** [comment]
Hey Luite,

No worries, I hope you had a great vacation!
I would appreciate your taking a closer look at them when you have a chance.

Thanks for your time,

Justin

**Comment by luite** [comment]
thanks, I'll do a bit more testing and then upload it to Hackage

**Comment by justinethier** [comment]
You're welcome, that sounds great.

**Pull request merged**
